package TMP.leetcode;

import java.util.Map;
import java.util.HashMap;

/**
 * <a href="https://leetcode.com/problems/find-the-difference/?envType=daily-question&envId=2023-09-25">...</a>
 * <p>
 * You are given two strings s and t.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Return the letter that was added to t.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        char res = 0;
        Map<Character, Integer> letterToCountMap = new HashMap<>();
        for (char ch : s.toCharArray()) {
            letterToCountMap.put(ch, letterToCountMap.getOrDefault(ch, 0) + 1);
        }
        for (char ch : t.toCharArray()) {
            int counter = letterToCountMap.getOrDefault(ch, 0);
            if (counter == 0) {
                res = ch;
                break;
            } else {
                letterToCountMap.put(ch, counter - 1);
            }
        }
        return res;
    }

    public char findTheDifference2(String s, String t) {
        int[] b = new int[256];
        for (char ch : s.toCharArray()) {
            b[ch] ^= ch;
        }
        for (char ch : t.toCharArray()) {
            b[ch] ^= ch;
        }
        for (int ch : b) {
            if ((char) ch != 0) {
                return (char) ch;
            }
        }
        return 0;
    }

}
